### ISSUE TITLE
Probleme calcul prezenta la vot

### ISSUE THREAD

**Issue by stefanvaduva** [gov-ithub/radar#2]
Salut,

Cred ca dataset-ul incarcat pe carto.com are ceva probleme. Prezenta la vot nu este calculata corect (la momentul scrierii acestui mesaj, Auckland are prezenta 500%). M-am uitat fugitiv peste cod in branch-urile "alegeri" si "website") si cred ca problema este in dataset, dar acolo nu am acces ca sa vad ce se intampla.

**Comment by stefanvaduva** [comment]
Am vazut acum ca de fapt procentul ala reprezinta nr de votanti raportat la numarul celor inscrisi pe liste si nu are legatura cu numarul celor cu drept de vot in tara respectiva. Cred ca vor fi multe neintelegeri pe tema asta. Poate ar fi utila o explicatie undeva sau chiar eliminarea acelui procent din popup.

**Comment by dan-barbulescu** [comment]
Într-adevăr, pentru diasporă sunt în unele locuri înscriși foarte puțini oameni (sau niciunul) pe listele secțiilor de vot și atunci pot apărea astfel de cifre.

Am renunțat la a prezenta datele în acest mod din cauza pericolului de a induce în eroare cetățenii.
